// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.grpc.demo.service;

public final class CountryServiceClass {
  private CountryServiceClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EmptyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Empty)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code Empty}
   */
  public static final class Empty extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Empty)
      EmptyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Empty.newBuilder() to construct.
    private Empty(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Empty() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Empty();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Empty(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpc.demo.service.CountryServiceClass.internal_static_Empty_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpc.demo.service.CountryServiceClass.internal_static_Empty_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpc.demo.service.CountryServiceClass.Empty.class, com.grpc.demo.service.CountryServiceClass.Empty.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.grpc.demo.service.CountryServiceClass.Empty)) {
        return super.equals(obj);
      }
      com.grpc.demo.service.CountryServiceClass.Empty other = (com.grpc.demo.service.CountryServiceClass.Empty) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.grpc.demo.service.CountryServiceClass.Empty parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.demo.service.CountryServiceClass.Empty parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.demo.service.CountryServiceClass.Empty parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.demo.service.CountryServiceClass.Empty parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.demo.service.CountryServiceClass.Empty parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.demo.service.CountryServiceClass.Empty parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.demo.service.CountryServiceClass.Empty parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpc.demo.service.CountryServiceClass.Empty parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpc.demo.service.CountryServiceClass.Empty parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.grpc.demo.service.CountryServiceClass.Empty parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpc.demo.service.CountryServiceClass.Empty parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpc.demo.service.CountryServiceClass.Empty parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.grpc.demo.service.CountryServiceClass.Empty prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Empty}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Empty)
        com.grpc.demo.service.CountryServiceClass.EmptyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.grpc.demo.service.CountryServiceClass.internal_static_Empty_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.grpc.demo.service.CountryServiceClass.internal_static_Empty_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.grpc.demo.service.CountryServiceClass.Empty.class, com.grpc.demo.service.CountryServiceClass.Empty.Builder.class);
      }

      // Construct using com.grpc.demo.service.CountryServiceClass.Empty.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.grpc.demo.service.CountryServiceClass.internal_static_Empty_descriptor;
      }

      @java.lang.Override
      public com.grpc.demo.service.CountryServiceClass.Empty getDefaultInstanceForType() {
        return com.grpc.demo.service.CountryServiceClass.Empty.getDefaultInstance();
      }

      @java.lang.Override
      public com.grpc.demo.service.CountryServiceClass.Empty build() {
        com.grpc.demo.service.CountryServiceClass.Empty result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.grpc.demo.service.CountryServiceClass.Empty buildPartial() {
        com.grpc.demo.service.CountryServiceClass.Empty result = new com.grpc.demo.service.CountryServiceClass.Empty(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.grpc.demo.service.CountryServiceClass.Empty) {
          return mergeFrom((com.grpc.demo.service.CountryServiceClass.Empty)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.grpc.demo.service.CountryServiceClass.Empty other) {
        if (other == com.grpc.demo.service.CountryServiceClass.Empty.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.grpc.demo.service.CountryServiceClass.Empty parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.grpc.demo.service.CountryServiceClass.Empty) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Empty)
    }

    // @@protoc_insertion_point(class_scope:Empty)
    private static final com.grpc.demo.service.CountryServiceClass.Empty DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.grpc.demo.service.CountryServiceClass.Empty();
    }

    public static com.grpc.demo.service.CountryServiceClass.Empty getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Empty>
        PARSER = new com.google.protobuf.AbstractParser<Empty>() {
      @java.lang.Override
      public Empty parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Empty(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Empty> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Empty> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.grpc.demo.service.CountryServiceClass.Empty getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CountryDTOOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CountryDTO)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 idCountry = 1;</code>
     * @return The idCountry.
     */
    long getIdCountry();

    /**
     * <code>int64 idRegion = 2;</code>
     * @return The idRegion.
     */
    long getIdRegion();

    /**
     * <code>string countryName = 3;</code>
     * @return The countryName.
     */
    java.lang.String getCountryName();
    /**
     * <code>string countryName = 3;</code>
     * @return The bytes for countryName.
     */
    com.google.protobuf.ByteString
        getCountryNameBytes();

    /**
     * <code>string regionName = 4;</code>
     * @return The regionName.
     */
    java.lang.String getRegionName();
    /**
     * <code>string regionName = 4;</code>
     * @return The bytes for regionName.
     */
    com.google.protobuf.ByteString
        getRegionNameBytes();

    /**
     * <code>string countryCodeMain = 5;</code>
     * @return The countryCodeMain.
     */
    java.lang.String getCountryCodeMain();
    /**
     * <code>string countryCodeMain = 5;</code>
     * @return The bytes for countryCodeMain.
     */
    com.google.protobuf.ByteString
        getCountryCodeMainBytes();

    /**
     * <code>int64 nationalDay = 6;</code>
     * @return The nationalDay.
     */
    long getNationalDay();
  }
  /**
   * Protobuf type {@code CountryDTO}
   */
  public static final class CountryDTO extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CountryDTO)
      CountryDTOOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CountryDTO.newBuilder() to construct.
    private CountryDTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CountryDTO() {
      countryName_ = "";
      regionName_ = "";
      countryCodeMain_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CountryDTO();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CountryDTO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              idCountry_ = input.readInt64();
              break;
            }
            case 16: {

              idRegion_ = input.readInt64();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              countryName_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              regionName_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              countryCodeMain_ = s;
              break;
            }
            case 48: {

              nationalDay_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpc.demo.service.CountryServiceClass.internal_static_CountryDTO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpc.demo.service.CountryServiceClass.internal_static_CountryDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpc.demo.service.CountryServiceClass.CountryDTO.class, com.grpc.demo.service.CountryServiceClass.CountryDTO.Builder.class);
    }

    public static final int IDCOUNTRY_FIELD_NUMBER = 1;
    private long idCountry_;
    /**
     * <code>int64 idCountry = 1;</code>
     * @return The idCountry.
     */
    @java.lang.Override
    public long getIdCountry() {
      return idCountry_;
    }

    public static final int IDREGION_FIELD_NUMBER = 2;
    private long idRegion_;
    /**
     * <code>int64 idRegion = 2;</code>
     * @return The idRegion.
     */
    @java.lang.Override
    public long getIdRegion() {
      return idRegion_;
    }

    public static final int COUNTRYNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object countryName_;
    /**
     * <code>string countryName = 3;</code>
     * @return The countryName.
     */
    @java.lang.Override
    public java.lang.String getCountryName() {
      java.lang.Object ref = countryName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        countryName_ = s;
        return s;
      }
    }
    /**
     * <code>string countryName = 3;</code>
     * @return The bytes for countryName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCountryNameBytes() {
      java.lang.Object ref = countryName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        countryName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REGIONNAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object regionName_;
    /**
     * <code>string regionName = 4;</code>
     * @return The regionName.
     */
    @java.lang.Override
    public java.lang.String getRegionName() {
      java.lang.Object ref = regionName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        regionName_ = s;
        return s;
      }
    }
    /**
     * <code>string regionName = 4;</code>
     * @return The bytes for regionName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRegionNameBytes() {
      java.lang.Object ref = regionName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        regionName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COUNTRYCODEMAIN_FIELD_NUMBER = 5;
    private volatile java.lang.Object countryCodeMain_;
    /**
     * <code>string countryCodeMain = 5;</code>
     * @return The countryCodeMain.
     */
    @java.lang.Override
    public java.lang.String getCountryCodeMain() {
      java.lang.Object ref = countryCodeMain_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        countryCodeMain_ = s;
        return s;
      }
    }
    /**
     * <code>string countryCodeMain = 5;</code>
     * @return The bytes for countryCodeMain.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCountryCodeMainBytes() {
      java.lang.Object ref = countryCodeMain_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        countryCodeMain_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NATIONALDAY_FIELD_NUMBER = 6;
    private long nationalDay_;
    /**
     * <code>int64 nationalDay = 6;</code>
     * @return The nationalDay.
     */
    @java.lang.Override
    public long getNationalDay() {
      return nationalDay_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (idCountry_ != 0L) {
        output.writeInt64(1, idCountry_);
      }
      if (idRegion_ != 0L) {
        output.writeInt64(2, idRegion_);
      }
      if (!getCountryNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, countryName_);
      }
      if (!getRegionNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, regionName_);
      }
      if (!getCountryCodeMainBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, countryCodeMain_);
      }
      if (nationalDay_ != 0L) {
        output.writeInt64(6, nationalDay_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (idCountry_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, idCountry_);
      }
      if (idRegion_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, idRegion_);
      }
      if (!getCountryNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, countryName_);
      }
      if (!getRegionNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, regionName_);
      }
      if (!getCountryCodeMainBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, countryCodeMain_);
      }
      if (nationalDay_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, nationalDay_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.grpc.demo.service.CountryServiceClass.CountryDTO)) {
        return super.equals(obj);
      }
      com.grpc.demo.service.CountryServiceClass.CountryDTO other = (com.grpc.demo.service.CountryServiceClass.CountryDTO) obj;

      if (getIdCountry()
          != other.getIdCountry()) return false;
      if (getIdRegion()
          != other.getIdRegion()) return false;
      if (!getCountryName()
          .equals(other.getCountryName())) return false;
      if (!getRegionName()
          .equals(other.getRegionName())) return false;
      if (!getCountryCodeMain()
          .equals(other.getCountryCodeMain())) return false;
      if (getNationalDay()
          != other.getNationalDay()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IDCOUNTRY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getIdCountry());
      hash = (37 * hash) + IDREGION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getIdRegion());
      hash = (37 * hash) + COUNTRYNAME_FIELD_NUMBER;
      hash = (53 * hash) + getCountryName().hashCode();
      hash = (37 * hash) + REGIONNAME_FIELD_NUMBER;
      hash = (53 * hash) + getRegionName().hashCode();
      hash = (37 * hash) + COUNTRYCODEMAIN_FIELD_NUMBER;
      hash = (53 * hash) + getCountryCodeMain().hashCode();
      hash = (37 * hash) + NATIONALDAY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getNationalDay());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.grpc.demo.service.CountryServiceClass.CountryDTO parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.demo.service.CountryServiceClass.CountryDTO parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.demo.service.CountryServiceClass.CountryDTO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.demo.service.CountryServiceClass.CountryDTO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.demo.service.CountryServiceClass.CountryDTO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.demo.service.CountryServiceClass.CountryDTO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.demo.service.CountryServiceClass.CountryDTO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpc.demo.service.CountryServiceClass.CountryDTO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpc.demo.service.CountryServiceClass.CountryDTO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.grpc.demo.service.CountryServiceClass.CountryDTO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpc.demo.service.CountryServiceClass.CountryDTO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpc.demo.service.CountryServiceClass.CountryDTO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.grpc.demo.service.CountryServiceClass.CountryDTO prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CountryDTO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CountryDTO)
        com.grpc.demo.service.CountryServiceClass.CountryDTOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.grpc.demo.service.CountryServiceClass.internal_static_CountryDTO_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.grpc.demo.service.CountryServiceClass.internal_static_CountryDTO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.grpc.demo.service.CountryServiceClass.CountryDTO.class, com.grpc.demo.service.CountryServiceClass.CountryDTO.Builder.class);
      }

      // Construct using com.grpc.demo.service.CountryServiceClass.CountryDTO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        idCountry_ = 0L;

        idRegion_ = 0L;

        countryName_ = "";

        regionName_ = "";

        countryCodeMain_ = "";

        nationalDay_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.grpc.demo.service.CountryServiceClass.internal_static_CountryDTO_descriptor;
      }

      @java.lang.Override
      public com.grpc.demo.service.CountryServiceClass.CountryDTO getDefaultInstanceForType() {
        return com.grpc.demo.service.CountryServiceClass.CountryDTO.getDefaultInstance();
      }

      @java.lang.Override
      public com.grpc.demo.service.CountryServiceClass.CountryDTO build() {
        com.grpc.demo.service.CountryServiceClass.CountryDTO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.grpc.demo.service.CountryServiceClass.CountryDTO buildPartial() {
        com.grpc.demo.service.CountryServiceClass.CountryDTO result = new com.grpc.demo.service.CountryServiceClass.CountryDTO(this);
        result.idCountry_ = idCountry_;
        result.idRegion_ = idRegion_;
        result.countryName_ = countryName_;
        result.regionName_ = regionName_;
        result.countryCodeMain_ = countryCodeMain_;
        result.nationalDay_ = nationalDay_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.grpc.demo.service.CountryServiceClass.CountryDTO) {
          return mergeFrom((com.grpc.demo.service.CountryServiceClass.CountryDTO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.grpc.demo.service.CountryServiceClass.CountryDTO other) {
        if (other == com.grpc.demo.service.CountryServiceClass.CountryDTO.getDefaultInstance()) return this;
        if (other.getIdCountry() != 0L) {
          setIdCountry(other.getIdCountry());
        }
        if (other.getIdRegion() != 0L) {
          setIdRegion(other.getIdRegion());
        }
        if (!other.getCountryName().isEmpty()) {
          countryName_ = other.countryName_;
          onChanged();
        }
        if (!other.getRegionName().isEmpty()) {
          regionName_ = other.regionName_;
          onChanged();
        }
        if (!other.getCountryCodeMain().isEmpty()) {
          countryCodeMain_ = other.countryCodeMain_;
          onChanged();
        }
        if (other.getNationalDay() != 0L) {
          setNationalDay(other.getNationalDay());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.grpc.demo.service.CountryServiceClass.CountryDTO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.grpc.demo.service.CountryServiceClass.CountryDTO) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long idCountry_ ;
      /**
       * <code>int64 idCountry = 1;</code>
       * @return The idCountry.
       */
      @java.lang.Override
      public long getIdCountry() {
        return idCountry_;
      }
      /**
       * <code>int64 idCountry = 1;</code>
       * @param value The idCountry to set.
       * @return This builder for chaining.
       */
      public Builder setIdCountry(long value) {
        
        idCountry_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 idCountry = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIdCountry() {
        
        idCountry_ = 0L;
        onChanged();
        return this;
      }

      private long idRegion_ ;
      /**
       * <code>int64 idRegion = 2;</code>
       * @return The idRegion.
       */
      @java.lang.Override
      public long getIdRegion() {
        return idRegion_;
      }
      /**
       * <code>int64 idRegion = 2;</code>
       * @param value The idRegion to set.
       * @return This builder for chaining.
       */
      public Builder setIdRegion(long value) {
        
        idRegion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 idRegion = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearIdRegion() {
        
        idRegion_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object countryName_ = "";
      /**
       * <code>string countryName = 3;</code>
       * @return The countryName.
       */
      public java.lang.String getCountryName() {
        java.lang.Object ref = countryName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          countryName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string countryName = 3;</code>
       * @return The bytes for countryName.
       */
      public com.google.protobuf.ByteString
          getCountryNameBytes() {
        java.lang.Object ref = countryName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          countryName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string countryName = 3;</code>
       * @param value The countryName to set.
       * @return This builder for chaining.
       */
      public Builder setCountryName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        countryName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string countryName = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCountryName() {
        
        countryName_ = getDefaultInstance().getCountryName();
        onChanged();
        return this;
      }
      /**
       * <code>string countryName = 3;</code>
       * @param value The bytes for countryName to set.
       * @return This builder for chaining.
       */
      public Builder setCountryNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        countryName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object regionName_ = "";
      /**
       * <code>string regionName = 4;</code>
       * @return The regionName.
       */
      public java.lang.String getRegionName() {
        java.lang.Object ref = regionName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          regionName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string regionName = 4;</code>
       * @return The bytes for regionName.
       */
      public com.google.protobuf.ByteString
          getRegionNameBytes() {
        java.lang.Object ref = regionName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          regionName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string regionName = 4;</code>
       * @param value The regionName to set.
       * @return This builder for chaining.
       */
      public Builder setRegionName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        regionName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string regionName = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearRegionName() {
        
        regionName_ = getDefaultInstance().getRegionName();
        onChanged();
        return this;
      }
      /**
       * <code>string regionName = 4;</code>
       * @param value The bytes for regionName to set.
       * @return This builder for chaining.
       */
      public Builder setRegionNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        regionName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object countryCodeMain_ = "";
      /**
       * <code>string countryCodeMain = 5;</code>
       * @return The countryCodeMain.
       */
      public java.lang.String getCountryCodeMain() {
        java.lang.Object ref = countryCodeMain_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          countryCodeMain_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string countryCodeMain = 5;</code>
       * @return The bytes for countryCodeMain.
       */
      public com.google.protobuf.ByteString
          getCountryCodeMainBytes() {
        java.lang.Object ref = countryCodeMain_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          countryCodeMain_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string countryCodeMain = 5;</code>
       * @param value The countryCodeMain to set.
       * @return This builder for chaining.
       */
      public Builder setCountryCodeMain(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        countryCodeMain_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string countryCodeMain = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearCountryCodeMain() {
        
        countryCodeMain_ = getDefaultInstance().getCountryCodeMain();
        onChanged();
        return this;
      }
      /**
       * <code>string countryCodeMain = 5;</code>
       * @param value The bytes for countryCodeMain to set.
       * @return This builder for chaining.
       */
      public Builder setCountryCodeMainBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        countryCodeMain_ = value;
        onChanged();
        return this;
      }

      private long nationalDay_ ;
      /**
       * <code>int64 nationalDay = 6;</code>
       * @return The nationalDay.
       */
      @java.lang.Override
      public long getNationalDay() {
        return nationalDay_;
      }
      /**
       * <code>int64 nationalDay = 6;</code>
       * @param value The nationalDay to set.
       * @return This builder for chaining.
       */
      public Builder setNationalDay(long value) {
        
        nationalDay_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 nationalDay = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearNationalDay() {
        
        nationalDay_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CountryDTO)
    }

    // @@protoc_insertion_point(class_scope:CountryDTO)
    private static final com.grpc.demo.service.CountryServiceClass.CountryDTO DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.grpc.demo.service.CountryServiceClass.CountryDTO();
    }

    public static com.grpc.demo.service.CountryServiceClass.CountryDTO getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CountryDTO>
        PARSER = new com.google.protobuf.AbstractParser<CountryDTO>() {
      @java.lang.Override
      public CountryDTO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CountryDTO(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CountryDTO> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CountryDTO> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.grpc.demo.service.CountryServiceClass.CountryDTO getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CountryListResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CountryListResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .CountryDTO countries = 1;</code>
     */
    java.util.List<com.grpc.demo.service.CountryServiceClass.CountryDTO> 
        getCountriesList();
    /**
     * <code>repeated .CountryDTO countries = 1;</code>
     */
    com.grpc.demo.service.CountryServiceClass.CountryDTO getCountries(int index);
    /**
     * <code>repeated .CountryDTO countries = 1;</code>
     */
    int getCountriesCount();
    /**
     * <code>repeated .CountryDTO countries = 1;</code>
     */
    java.util.List<? extends com.grpc.demo.service.CountryServiceClass.CountryDTOOrBuilder> 
        getCountriesOrBuilderList();
    /**
     * <code>repeated .CountryDTO countries = 1;</code>
     */
    com.grpc.demo.service.CountryServiceClass.CountryDTOOrBuilder getCountriesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code CountryListResponse}
   */
  public static final class CountryListResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CountryListResponse)
      CountryListResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CountryListResponse.newBuilder() to construct.
    private CountryListResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CountryListResponse() {
      countries_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CountryListResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CountryListResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                countries_ = new java.util.ArrayList<com.grpc.demo.service.CountryServiceClass.CountryDTO>();
                mutable_bitField0_ |= 0x00000001;
              }
              countries_.add(
                  input.readMessage(com.grpc.demo.service.CountryServiceClass.CountryDTO.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          countries_ = java.util.Collections.unmodifiableList(countries_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpc.demo.service.CountryServiceClass.internal_static_CountryListResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpc.demo.service.CountryServiceClass.internal_static_CountryListResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpc.demo.service.CountryServiceClass.CountryListResponse.class, com.grpc.demo.service.CountryServiceClass.CountryListResponse.Builder.class);
    }

    public static final int COUNTRIES_FIELD_NUMBER = 1;
    private java.util.List<com.grpc.demo.service.CountryServiceClass.CountryDTO> countries_;
    /**
     * <code>repeated .CountryDTO countries = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.grpc.demo.service.CountryServiceClass.CountryDTO> getCountriesList() {
      return countries_;
    }
    /**
     * <code>repeated .CountryDTO countries = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.grpc.demo.service.CountryServiceClass.CountryDTOOrBuilder> 
        getCountriesOrBuilderList() {
      return countries_;
    }
    /**
     * <code>repeated .CountryDTO countries = 1;</code>
     */
    @java.lang.Override
    public int getCountriesCount() {
      return countries_.size();
    }
    /**
     * <code>repeated .CountryDTO countries = 1;</code>
     */
    @java.lang.Override
    public com.grpc.demo.service.CountryServiceClass.CountryDTO getCountries(int index) {
      return countries_.get(index);
    }
    /**
     * <code>repeated .CountryDTO countries = 1;</code>
     */
    @java.lang.Override
    public com.grpc.demo.service.CountryServiceClass.CountryDTOOrBuilder getCountriesOrBuilder(
        int index) {
      return countries_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < countries_.size(); i++) {
        output.writeMessage(1, countries_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < countries_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, countries_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.grpc.demo.service.CountryServiceClass.CountryListResponse)) {
        return super.equals(obj);
      }
      com.grpc.demo.service.CountryServiceClass.CountryListResponse other = (com.grpc.demo.service.CountryServiceClass.CountryListResponse) obj;

      if (!getCountriesList()
          .equals(other.getCountriesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getCountriesCount() > 0) {
        hash = (37 * hash) + COUNTRIES_FIELD_NUMBER;
        hash = (53 * hash) + getCountriesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.grpc.demo.service.CountryServiceClass.CountryListResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.demo.service.CountryServiceClass.CountryListResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.demo.service.CountryServiceClass.CountryListResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.demo.service.CountryServiceClass.CountryListResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.demo.service.CountryServiceClass.CountryListResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.demo.service.CountryServiceClass.CountryListResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.demo.service.CountryServiceClass.CountryListResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpc.demo.service.CountryServiceClass.CountryListResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpc.demo.service.CountryServiceClass.CountryListResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.grpc.demo.service.CountryServiceClass.CountryListResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpc.demo.service.CountryServiceClass.CountryListResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpc.demo.service.CountryServiceClass.CountryListResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.grpc.demo.service.CountryServiceClass.CountryListResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CountryListResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CountryListResponse)
        com.grpc.demo.service.CountryServiceClass.CountryListResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.grpc.demo.service.CountryServiceClass.internal_static_CountryListResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.grpc.demo.service.CountryServiceClass.internal_static_CountryListResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.grpc.demo.service.CountryServiceClass.CountryListResponse.class, com.grpc.demo.service.CountryServiceClass.CountryListResponse.Builder.class);
      }

      // Construct using com.grpc.demo.service.CountryServiceClass.CountryListResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCountriesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (countriesBuilder_ == null) {
          countries_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          countriesBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.grpc.demo.service.CountryServiceClass.internal_static_CountryListResponse_descriptor;
      }

      @java.lang.Override
      public com.grpc.demo.service.CountryServiceClass.CountryListResponse getDefaultInstanceForType() {
        return com.grpc.demo.service.CountryServiceClass.CountryListResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.grpc.demo.service.CountryServiceClass.CountryListResponse build() {
        com.grpc.demo.service.CountryServiceClass.CountryListResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.grpc.demo.service.CountryServiceClass.CountryListResponse buildPartial() {
        com.grpc.demo.service.CountryServiceClass.CountryListResponse result = new com.grpc.demo.service.CountryServiceClass.CountryListResponse(this);
        int from_bitField0_ = bitField0_;
        if (countriesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            countries_ = java.util.Collections.unmodifiableList(countries_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.countries_ = countries_;
        } else {
          result.countries_ = countriesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.grpc.demo.service.CountryServiceClass.CountryListResponse) {
          return mergeFrom((com.grpc.demo.service.CountryServiceClass.CountryListResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.grpc.demo.service.CountryServiceClass.CountryListResponse other) {
        if (other == com.grpc.demo.service.CountryServiceClass.CountryListResponse.getDefaultInstance()) return this;
        if (countriesBuilder_ == null) {
          if (!other.countries_.isEmpty()) {
            if (countries_.isEmpty()) {
              countries_ = other.countries_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCountriesIsMutable();
              countries_.addAll(other.countries_);
            }
            onChanged();
          }
        } else {
          if (!other.countries_.isEmpty()) {
            if (countriesBuilder_.isEmpty()) {
              countriesBuilder_.dispose();
              countriesBuilder_ = null;
              countries_ = other.countries_;
              bitField0_ = (bitField0_ & ~0x00000001);
              countriesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getCountriesFieldBuilder() : null;
            } else {
              countriesBuilder_.addAllMessages(other.countries_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.grpc.demo.service.CountryServiceClass.CountryListResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.grpc.demo.service.CountryServiceClass.CountryListResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.grpc.demo.service.CountryServiceClass.CountryDTO> countries_ =
        java.util.Collections.emptyList();
      private void ensureCountriesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          countries_ = new java.util.ArrayList<com.grpc.demo.service.CountryServiceClass.CountryDTO>(countries_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.grpc.demo.service.CountryServiceClass.CountryDTO, com.grpc.demo.service.CountryServiceClass.CountryDTO.Builder, com.grpc.demo.service.CountryServiceClass.CountryDTOOrBuilder> countriesBuilder_;

      /**
       * <code>repeated .CountryDTO countries = 1;</code>
       */
      public java.util.List<com.grpc.demo.service.CountryServiceClass.CountryDTO> getCountriesList() {
        if (countriesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(countries_);
        } else {
          return countriesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .CountryDTO countries = 1;</code>
       */
      public int getCountriesCount() {
        if (countriesBuilder_ == null) {
          return countries_.size();
        } else {
          return countriesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .CountryDTO countries = 1;</code>
       */
      public com.grpc.demo.service.CountryServiceClass.CountryDTO getCountries(int index) {
        if (countriesBuilder_ == null) {
          return countries_.get(index);
        } else {
          return countriesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .CountryDTO countries = 1;</code>
       */
      public Builder setCountries(
          int index, com.grpc.demo.service.CountryServiceClass.CountryDTO value) {
        if (countriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCountriesIsMutable();
          countries_.set(index, value);
          onChanged();
        } else {
          countriesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .CountryDTO countries = 1;</code>
       */
      public Builder setCountries(
          int index, com.grpc.demo.service.CountryServiceClass.CountryDTO.Builder builderForValue) {
        if (countriesBuilder_ == null) {
          ensureCountriesIsMutable();
          countries_.set(index, builderForValue.build());
          onChanged();
        } else {
          countriesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CountryDTO countries = 1;</code>
       */
      public Builder addCountries(com.grpc.demo.service.CountryServiceClass.CountryDTO value) {
        if (countriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCountriesIsMutable();
          countries_.add(value);
          onChanged();
        } else {
          countriesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .CountryDTO countries = 1;</code>
       */
      public Builder addCountries(
          int index, com.grpc.demo.service.CountryServiceClass.CountryDTO value) {
        if (countriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCountriesIsMutable();
          countries_.add(index, value);
          onChanged();
        } else {
          countriesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .CountryDTO countries = 1;</code>
       */
      public Builder addCountries(
          com.grpc.demo.service.CountryServiceClass.CountryDTO.Builder builderForValue) {
        if (countriesBuilder_ == null) {
          ensureCountriesIsMutable();
          countries_.add(builderForValue.build());
          onChanged();
        } else {
          countriesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CountryDTO countries = 1;</code>
       */
      public Builder addCountries(
          int index, com.grpc.demo.service.CountryServiceClass.CountryDTO.Builder builderForValue) {
        if (countriesBuilder_ == null) {
          ensureCountriesIsMutable();
          countries_.add(index, builderForValue.build());
          onChanged();
        } else {
          countriesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CountryDTO countries = 1;</code>
       */
      public Builder addAllCountries(
          java.lang.Iterable<? extends com.grpc.demo.service.CountryServiceClass.CountryDTO> values) {
        if (countriesBuilder_ == null) {
          ensureCountriesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, countries_);
          onChanged();
        } else {
          countriesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .CountryDTO countries = 1;</code>
       */
      public Builder clearCountries() {
        if (countriesBuilder_ == null) {
          countries_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          countriesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .CountryDTO countries = 1;</code>
       */
      public Builder removeCountries(int index) {
        if (countriesBuilder_ == null) {
          ensureCountriesIsMutable();
          countries_.remove(index);
          onChanged();
        } else {
          countriesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .CountryDTO countries = 1;</code>
       */
      public com.grpc.demo.service.CountryServiceClass.CountryDTO.Builder getCountriesBuilder(
          int index) {
        return getCountriesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .CountryDTO countries = 1;</code>
       */
      public com.grpc.demo.service.CountryServiceClass.CountryDTOOrBuilder getCountriesOrBuilder(
          int index) {
        if (countriesBuilder_ == null) {
          return countries_.get(index);  } else {
          return countriesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .CountryDTO countries = 1;</code>
       */
      public java.util.List<? extends com.grpc.demo.service.CountryServiceClass.CountryDTOOrBuilder> 
           getCountriesOrBuilderList() {
        if (countriesBuilder_ != null) {
          return countriesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(countries_);
        }
      }
      /**
       * <code>repeated .CountryDTO countries = 1;</code>
       */
      public com.grpc.demo.service.CountryServiceClass.CountryDTO.Builder addCountriesBuilder() {
        return getCountriesFieldBuilder().addBuilder(
            com.grpc.demo.service.CountryServiceClass.CountryDTO.getDefaultInstance());
      }
      /**
       * <code>repeated .CountryDTO countries = 1;</code>
       */
      public com.grpc.demo.service.CountryServiceClass.CountryDTO.Builder addCountriesBuilder(
          int index) {
        return getCountriesFieldBuilder().addBuilder(
            index, com.grpc.demo.service.CountryServiceClass.CountryDTO.getDefaultInstance());
      }
      /**
       * <code>repeated .CountryDTO countries = 1;</code>
       */
      public java.util.List<com.grpc.demo.service.CountryServiceClass.CountryDTO.Builder> 
           getCountriesBuilderList() {
        return getCountriesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.grpc.demo.service.CountryServiceClass.CountryDTO, com.grpc.demo.service.CountryServiceClass.CountryDTO.Builder, com.grpc.demo.service.CountryServiceClass.CountryDTOOrBuilder> 
          getCountriesFieldBuilder() {
        if (countriesBuilder_ == null) {
          countriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.grpc.demo.service.CountryServiceClass.CountryDTO, com.grpc.demo.service.CountryServiceClass.CountryDTO.Builder, com.grpc.demo.service.CountryServiceClass.CountryDTOOrBuilder>(
                  countries_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          countries_ = null;
        }
        return countriesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CountryListResponse)
    }

    // @@protoc_insertion_point(class_scope:CountryListResponse)
    private static final com.grpc.demo.service.CountryServiceClass.CountryListResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.grpc.demo.service.CountryServiceClass.CountryListResponse();
    }

    public static com.grpc.demo.service.CountryServiceClass.CountryListResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CountryListResponse>
        PARSER = new com.google.protobuf.AbstractParser<CountryListResponse>() {
      @java.lang.Override
      public CountryListResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CountryListResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CountryListResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CountryListResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.grpc.demo.service.CountryServiceClass.CountryListResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Empty_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Empty_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CountryDTO_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CountryDTO_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CountryListResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CountryListResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rservice.proto\"\007\n\005Empty\"\210\001\n\nCountryDTO\022" +
      "\021\n\tidCountry\030\001 \001(\003\022\020\n\010idRegion\030\002 \001(\003\022\023\n\013" +
      "countryName\030\003 \001(\t\022\022\n\nregionName\030\004 \001(\t\022\027\n" +
      "\017countryCodeMain\030\005 \001(\t\022\023\n\013nationalDay\030\006 " +
      "\001(\003\"5\n\023CountryListResponse\022\036\n\tcountries\030" +
      "\001 \003(\0132\013.CountryDTO2_\n\016CountryService\022\'\n\007" +
      "GetList\022\006.Empty\032\024.CountryListResponse\022$\n" +
      "\rUpdateCountry\022\013.CountryDTO\032\006.EmptyB,\n\025c" +
      "om.grpc.demo.serviceB\023CountryServiceClas" +
      "sb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Empty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_CountryDTO_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CountryDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CountryDTO_descriptor,
        new java.lang.String[] { "IdCountry", "IdRegion", "CountryName", "RegionName", "CountryCodeMain", "NationalDay", });
    internal_static_CountryListResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_CountryListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CountryListResponse_descriptor,
        new java.lang.String[] { "Countries", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
